# Generated by Django 4.1 on 2023-02-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_order_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_list',
            field=models.TextField(null=True),
        ),
    ]
